language: node_js

node_js:

  - "0.10"
  - "0.12"

before_install:
  # Fire up xvfb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "sleep 3"

install:
  - "npm install"

script:
  - "npm start &"
  - "selenium-standalone start"
  - "npm test"
